name: openmmdl  # Name of the Conda environment

channels:
  - conda-forge  # Add the conda-forge channel here
  - nodefaults

dependencies:
  - pip
  - setuptools>=61.0
  - versioningit~=2.0
  - sqlite>=3.40
  - pytest>=6.1.2
  - pytest-runner
  - numpy~=2.2.6
  - plip
  - requests>=2.28.1
  - rdkit>=2022.03.5
  - mdtraj
  - pdbfixer
  - openff-toolkit
  - openmmforcefields
  - openmm>=8.3.1
  - cuda-toolkit
  - cuda-python>=11.7.1
  - mdanalysis>=2.3.0
  - pytest-shutil>=1.7.0
  - flask>=2.2.2
  - cairosvg
  - nglview
  - mdonatello
  - numba>=0.59.1
  - jupyter
  - prolif>=2.1.0
  # Add any additional runtime dependencies from pyproject.toml here
  # - package_name=version
